server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 'validate' in prod once Flyway/Liquibase manages schema
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
info:
  app:
    name: Customer Service
    description: Manages corporate customers and corporate users for CIB platform
